version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: lakehouse-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse_net

  postgres:
    image: postgres:15-alpine
    container_name: lakehouse_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lakehouse_net

  airflow:
    build: .
    image: custom-airflow:2.8.1
    container_name: lakehouse_airflow
    depends_on:
      - postgres
      - minio
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@postgres:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      # --- Cấu hình kết nối PostgreSQL cho tầng Gold ---
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=airflow_db
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow_password
      # --- Cấu hình MinIO ---
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./tests:/opt/airflow/tests
    ports:
      - "8080:8080"
    command: bash -c "airflow webserver & airflow scheduler"
    networks:
      - lakehouse_net

  metabase:
    image: metabase/metabase:latest
    container_name: lakehouse_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data
    networks:
      - lakehouse_net

volumes:
  minio_data:
  postgres_data:
  metabase_data:

networks:
  lakehouse_net:
    driver: bridge